name: Firebase Debug Token CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  # 手動でワークフローを実行するためのトリガーを追加

jobs:
  manage-token:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Decrypt Firebase App Check Debug Token
        env:
          APP_CHECK_DEBUG_TOKEN_FROM_CI: ${{ secrets.FIREBASE_APP_CHECK_DEBUG_TOKEN }}
        run: |
          echo "Firebase App Check Debug Token decrypted and ready to use"
          # 必要に応じて追加のステップをここに記述
