name: Firebase Debug Token CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Firebase App Check Debug Token
        env:
          APP_CHECK_DEBUG_TOKEN_FROM_CI: F6BA344C-5499-4412-8499-7244B3A0859C
        run: |
          echo "Using Firebase App Check Debug Token..."
          ./gradlew appCheckDebug