name: Firebase Debug Token CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  manage-token:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Decrypt Firebase App Check Debug Token
        env:
          APP_CHECK_DEBUG_TOKEN_FROM_CI: ${{ secrets.FIREBASE_APP_CHECK_DEBUG_TOKEN }}
        run: |
          echo "Firebase App Check Debug Token decrypted and ready to use"
          # Add any additional steps if necessary