name: Firebase Debug Token CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  manage-token:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode and save Android Keystore
        run: |
          echo ${{ secrets.ANDROID_KEYSTORE }} | base64 --decode > $HOME/fintech.keystore

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Run Firebase Test
        run: ./gradlew test
